/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#13131b",
        "on-background": "#e4e1ed",
        surface: "#13131b",
        "surface-dim": "#13131b",
        "surface-bright": "#393841",
        "surface-container-lowest": "#0d0d15",
        "surface-container-low": "#1b1b23",
        "surface-container": "#1f1f27",
        "surface-container-high": "#292932",
        "surface-container-highest": "#34343d",
        "surface-variant": "#34343d",
        "on-surface": "#e4e1ed",
        "on-surface-variant": "#c7c4d7",
        outline: "#908fa0",
        "outline-variant": "#464554",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "inverse-primary": "#494bd6",
        secondary: "#ddb7ff",
        "on-secondary": "#490080",
        "secondary-container": "#6f00be",
        "on-secondary-container": "#d6a9ff",
        tertiary: "#ffb783",
        "tertiary-container": "#d97721",
        "on-tertiary-container": "#452000",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "success-emerald": "#10b981",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "panel-gap": "1px",
        "container-margin": "24px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
        "body-base": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "code-base": ["JetBrains Mono", "ui-monospace", "monospace"],
        "code-sm": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code-base": ["13px", { lineHeight: "20px", fontWeight: "450" }],
        "code-sm": ["11px", { lineHeight: "16px", fontWeight: "450" }],
      },
    },
  },
  plugins: [],
};
